vm_types:
- name: common
  cloud_properties:
    machine_type: n1-standard-2
    root_disk_size_gb: 20
    root_disk_type: pd-ssd

- name: worker
  cloud_properties:
    machine_type: n1-standard-4
    root_disk_size_gb: 100
    root_disk_type: pd-ssd

vm_extensions:
- name: concourse-lb
  cloud_properties:
    target_pool: concourse-target-pool

compilation:
  workers: 2
  network: public
  reuse_compilation_vms: true
  cloud_properties:
    machine_type: n1-standard-4
    root_disk_size_gb: 100
    root_disk_type: pd-ssd
    preemptible: true

networks:
  - name: public
    type: manual
    subnets:
    - azs:
      - europe-west1-c
      cloud_properties:
        network_name: amcginlay-pcf-network
        subnetwork_name: amcginlay-bosh-subnet
      dns:
      - 169.254.169.254
      - 8.8.8.8
      gateway: 10.0.1.1
      range: 10.0.1.0/24
      reserved: []
      static:
      - 10.0.1.2-10.0.1.50

  - name: vip
    type: vip
    
disk_types:
- name: database
  disk_size: 10240